apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/cloudcrafts-by-vivek/rollouts-demo.git
  password: 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
  username: cloudcrafts-by-vivek