apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: "{{ .Release.Name }}-app"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 20s} # Wait 20 seconds before proceeding
      - setWeight: 50
      - pause: {} # Pause indefinitely until manually promoted